spring:
  config:
    import: optional:file:.env.test[.properties]
  data:
    redis:
      password: ${SPRING__DATA__REDIS__PASSWORD:test_redis_password_change_me}
  datasource:
    password: ${SPRING__DATASOURCE__PASSWORD:test_db_password_change_me}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: com.back.global.jpa.config.CustomTestPostgreSQLDialect
        jdbc:
          batch_size: 0
          order_inserts: false
custom:
  admin:
    username: admin
  jwt:
    secretKey: "${CUSTOM__JWT__SECRET_KEY:abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789}"
  site:
    cookieDomain: "${custom.test.cookieDomain}"
    frontUrl: "${custom.test.frontUrl}"
    backUrl: "${custom.test.backUrl}"
    dbHost: "${custom.test.dbHost}"
    dbPort: "${custom.test.dbPort}"
    dbName: "${custom.test.dbName}"
    redisHost: "${custom.test.redisHost}"
    redisPort: "${custom.test.redisPort}"
    redisDatabase: "${custom.test.redisDatabase}"
