springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
spring:
  data:
    redis:
      password: "${PROD___SPRING__DATA__REDIS__PASSWORD}"
  datasource:
    password: "${PROD___SPRING__DATASOURCE__PASSWORD}"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
    show-sql: false
  sql:
    init:
      mode: never
logging:
  level:
    com.back: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.hibernate.orm.jdbc.batch: INFO
    org.springframework.transaction.interceptor: INFO
custom:
  pgroonga:
    required: true
  jpa:
    after-ddl:
      failOnError: true
  site:
    cookieDomain: "${custom.prod.cookieDomain}"
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"
    dbHost: "${custom.prod.dbHost}"
    dbName: "${custom.prod.dbName}"
    redisHost: "${custom.prod.redisHost}"
    redisDatabase: "${custom.prod.redisDatabase}"
